config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users, :path => 'accounts', controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show] do
    resources :reading_lists
  end
  post 'users/:user_id/reading_lists/new' => 'reading_lists#new'
  post 'users/:user_id/reading_lists/:id/edit' => 'reading_lists#edit'
  delete 'users/:user_id/reading_lists/:id' => 'reading_lists#destroy'
  patch 'articles/:id' => 'articles#update'
  resources :articles, only: [:show, :edit, :update]
  resources :categories, only: [:index, :show] do
    resources :subcategories, only: [:show]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reading_list.rb
class ReadingList < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  belongs_to :user
  has_many :articles
end

app/controllers/reading_lists_controller.rb
class ReadingListsController < ApplicationController
  before_action :require_login
  before_action :set_reading_list, only: [:show, :edit, :update, :destroy]

  def index
  end

  def new
    @reading_list = ReadingList.new
    render :layout => false
  end

  def create
    #binding.pry
    @reading_list = current_user.reading_lists.create(reading_list_params)
    if @reading_list.save
      render json: @reading_list, status: 201
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    @reading_list.update(reading_list_params)
    redirect_to user_reading_list_path(current_user.id, @reading_list)
  end

  def destroy
    @reading_list.destroy
    redirect_to user_reading_lists_path
  end

  private

  def reading_list_params
    params.require(:reading_list).permit(:name, :user_id)
  end

  def set_reading_list
    @reading_list = ReadingList.find(params[:id])
  end

  def require_login
    unless user_signed_in?
      flash[:error] = "You must be logged in to save"
      redirect_to new_user_session_path
    end
  end
end

app/helpers/reading_lists_helper.rb
module ReadingListsHelper
end

app/views/reading_lists/_form.html.erb
<%= form_for [current_user, @reading_list] do |f| %>
  <% if @reading_list.errors.any? %>
    <div id="error_explanation">
      <p>Sorry, please try again:</p>

      <ul>
      <% @reading_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/reading_lists/edit.html.erb
<h1>Edit Reading List</h1>

<%= render 'form' %>

app/views/reading_lists/index.html.erb
<% if current_user.reading_lists.count > 1 %>
  <h1>Your Reading List(s)</h1>
<% elsif current_user.reading_lists.count == 1 %>
  <h1>Your Reading List</h1>
<% end %>

<ul class="reading_lists">
  <% current_user.reading_lists.each do |reading_list| %>
    <li class="list_links"><%= link_to reading_list.name, user_reading_list_path(current_user.id, reading_list.id) %></li>
  <% end %>
</ul>

<!--<%= button_to "Create a Reading List", new_user_reading_list_path(current_user.id) %> -->
<button type="submit" name="button" data-url="/users/<%= current_user.id %>/reading_lists/new">Create a Reading List</button><br>
<%= javascript_include_tag "reading_lists" %>

app/views/reading_lists/new.html.erb
<h2>Create New Reading List</h2>

<%= render 'form' %>

app/views/reading_lists/show.html.erb
<h1><%= @reading_list.name %></h1>

<% if @reading_list.articles.count < 1 %>
  <p><i>This list is currently empty...</i></p><br>
  <%= link_to "Browse Articles", root_path %>
<% end %>

<ul>
  <% @reading_list.articles.each do |article| %>
    <li><%= link_to article.name, article_path(article.id) %></li>
  <% end %>
</ul>

<%= button_to "Edit Reading List", {:controller => :reading_lists, :action => 'edit', :id => @reading_list.id }, :method => :edit %>
<%= button_to "Delete Reading List", {:controller => :reading_lists, :action => 'destroy', :id => @reading_list.id }, :method => :delete %>