config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users, :path => 'accounts', controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show] do
    resources :reading_lists
  end
  post 'users/:user_id/reading_lists/new' => 'reading_lists#new'
  post 'users/:user_id/reading_lists/:id/edit' => 'reading_lists#edit'
  delete 'users/:user_id/reading_lists/:id' => 'reading_lists#destroy'
  patch 'articles/:id' => 'articles#update'
  resources :articles, only: [:show, :edit, :update]
  resources :categories, only: [:index, :show] do
    resources :subcategories, only: [:show]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subcategory.rb
require_dependency '../validators/url_validator.rb'

class Subcategory < ApplicationRecord
  validates :name, presence: true
  validates :url, url: true
  belongs_to :category
  has_many :articles
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController

  def show
    @subcategory = Subcategory.find(params[:id])
    scrape_articles(@subcategory)
    @subcategory.articles
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @subcategory }
    end
  end

end

app/views/subcategories/show.html.erb
<h1><%= @subcategory.name %></h1>

<% if @subcategory.articles.count == 0 %>
  <p>Sorry, please try again later!</p>
<% else %>
  <ul>
    <% @subcategory.articles.each do |article| %>
      <li><%= link_to article.name, article_path(article.id) %></li>
    <% end %>
  </ul>
<% end %>

<%= link_to "<- Back", category_path(@subcategory.category_id) %>