config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users, :path => 'accounts', controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show] do
    resources :reading_lists
  end
  post 'users/:user_id/reading_lists/new' => 'reading_lists#new'
  post 'users/:user_id/reading_lists/:id/edit' => 'reading_lists#edit'
  delete 'users/:user_id/reading_lists/:id' => 'reading_lists#destroy'
  patch 'articles/:id' => 'articles#update'
  resources :articles, only: [:show, :edit, :update]
  resources :categories, only: [:index, :show] do
    resources :subcategories, only: [:show]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
require_dependency '../validators/url_validator.rb'

class Article < ApplicationRecord
  validates :name, presence: true
  validates :url, url: true
  belongs_to :reading_list, optional: true
  accepts_nested_attributes_for :reading_list
  belongs_to :category
  belongs_to :subcategory

  def self.most_saved
    Article.where.not(reading_list_id: nil)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_login, except: :show
  before_action :set_article, only: [:show, :edit, :update]

  def show
    #@article.build_reading_list
    respond_to do |format|
      format.html { render :show }
      format.json { render json: @article }
    end
  end

  def edit
    render :show
  end

  def update
    if params[:article][:reading_list_id] != ""
      reading_list = current_user.reading_lists.find_by(id: params[:article][:reading_list_id])
      reading_list.articles << @article
    elsif params[:article][:reading_list_attributes][:name] != nil || params[:article][:reading_list_attributes][:name] != ""
      reading_list = current_user.reading_lists.find_or_create_by(name: params[:article][:reading_list_attributes][:name])
      reading_list.articles << @article
    end

    if @article.save(article_params)
      redirect_to user_reading_list_path(current_user.id, reading_list.id)
    else
      render :show
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:reading_list_id, reading_list_attributes: [:id, :name, :user_id])
  end

  def require_login
    unless user_signed_in?
      flash[:error] = "You must be logged in to save"
      redirect_to new_user_session_path
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/show.html.erb
<h1 class="articleName"><%= @article.name %></h1>
<p><a href="<%= @article.url %>" class="articleUrl">Click here to read</a></p>

<% if current_user %>
  <h3>Select a Reading List, or Enter a Name to Create a New List:</h3>
    <%= form_for @article do |f| %>
      <% if @article.errors.any? %>
        <div id="error_explanation">
          <p>Sorry, please try again:</p>
          <ul>
            <% @article.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <%= f.collection_select :reading_list_id, current_user.reading_lists.all, :id, :name, {:include_blank => true} %>
      <%= f.fields_for :reading_list, @article.build_reading_list do |reading_list_field| %>
        <%= reading_list_field.text_field :name %>
        <% end %>

      <%= f.submit "Save to Reading List" %>
    <% end %>
<% else %>
  <%= button_to "Save", edit_article_path, method: "get" %><br>
<% end %>

<%= link_to "<- Back", category_subcategory_path(@article.category_id, @article.subcategory_id) %>
<a href="#" class="js-next" data-id="<%= @article.id %>">Next Article -></a>
<%= javascript_include_tag "articles" %>