config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users, :path => 'accounts', controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users, only: [:show] do
    resources :reading_lists
  end
  post 'users/:user_id/reading_lists/new' => 'reading_lists#new'
  post 'users/:user_id/reading_lists/:id/edit' => 'reading_lists#edit'
  delete 'users/:user_id/reading_lists/:id' => 'reading_lists#destroy'
  patch 'articles/:id' => 'articles#update'
  resources :articles, only: [:show, :edit, :update]
  resources :categories, only: [:index, :show] do
    resources :subcategories, only: [:show]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_header.html.erb
<ul>
  <% if current_user && current_user.reading_lists %>
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Your Reading List(s)", user_reading_lists_path(current_user.reading_lists) %></li>
  <% end%>
  <%= render 'layouts/sign_in' %>
</ul>

app/views/layouts/_sign_in.html.erb
<% if user_signed_in? %>
  <li><%= "Signed in as: #{current_user.email}" %></li>
  <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
<% else %>
  <%= link_to "Sign In", new_user_session_path %>
  <%= link_to "Sign In with Google", user_google_oauth2_omniauth_authorize_path %>
  <%= link_to "Sign Up", new_user_registration_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReadLater</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    
    <%= yield %>
  </body>
</html>